# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  
  config.vm.box = "ubuntu/bionic64"

  
   config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  
  config.vm.provision "file", source: "j:/boxes/vagrr/file.txt", destination: "/home/vagrant/file.txt"
  
  config.vm.provision "shell", inline: <<-SHELL
     sudo apt-get update
     sudo apt-get install -y python3
	 sudo apt-get install -y python3-pip
	 sudo apt-get install -y python3-psycopg2
	 sudo apt-get install -y python3-django
   SHELL

  
  
  
  
  
  
  
  
end
